version: '3'
services:
  bot:
    image: "test"
    restart: always
    env_file: .env
    depends_on:
    - db
  db:
    image: mysql:8
    restart: always
    container_name: mysql 
    env_file: .env
    volumes:
    - mysql-volume:/var/lib/mysql
    ports:
    - 127.0.0.1:3306:3306


volumes:
  mysql-volume: